version: '3.8'

services:
  ka9q-radio:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: ka9q-radio:latest
    container_name: ka9q-radio
    privileged: true
    restart: unless-stopped
    
    # Use external bridge network for multicast communication with ubersdr
    networks:
      - sdr-network
    
    volumes:
      # Mount USB devices for SDR hardware access
      - /dev/bus/usb:/dev/bus/usb
      # Persistent configuration - initialized from templates on first run
      # Edit configs in the volume, they will persist across container restarts
      # To reset to defaults, delete the volume: docker volume rm docker_radiod-config
      - radiod-config:/etc/ka9q-radio
      # Persistent data directory for recordings and wisdom
      - radiod-data:/var/lib/ka9q-radio
      # Optional: Mount custom configuration from host (overrides persistent volume)
      # - ./radiod@ubersdr.conf:/etc/ka9q-radio/radiod@ubersdr.conf
    
    environment:
      - TZ=${TZ:-UTC}
    
    # Optional: Override the default command to use a different config
    # command: ["/usr/local/sbin/radiod", "/etc/ka9q-radio/radiod@custom.conf"]
    
    # Healthcheck
    healthcheck:
      test: ["CMD", "pgrep", "-x", "radiod"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

# External network shared with ubersdr container
# Create with: docker network create sdr-network --subnet 172.20.0.0/16
networks:
  sdr-network:
    external: true

volumes:
  radiod-config:
  radiod-data: